# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164yj7PNY1Ma3Nfg6Sanbb-32rkpPYuGd
"""

import simpy 
import os
import pandas as pd
# Generator function that defines the working of the traffic light 
# "timeout()" function makes next yield statement wait for a 
# given time passed as the argument 
traffic_light=[]
def Traffic_Light(env):
  
        while True:

            traffic_light.append("Light turns GRN at " + str(env.now))

            # Light is green for 25 seconds
            yield env.timeout(25)

            traffic_light.append("Light turns YEL at " + str(env.now))

            # Light is yellow for 5 seconds
            yield env.timeout(5)

            #traffic_light.append("Light turns RED at " + str(env.now))

            # Light is red for 60 seconds
            yield env.timeout(60)

            '''the function below is to put constrain on the file size, it will follow this flow:
            1) Check if the file exists.
            2)If file exists then go to the next path if not then create the file.
            3)if file exists then it will check if the file size is bigger than the specified contrain, 
            if found bigger then it will execute the print statement. Else it wil pass the flow to next statement 
            where while condition is there to check and until while condition is true the data will be written in csv
            when condition becomes false the process stops.          
            '''
            if os.path.exists('traffic.csv') != True:
                with open('traffic.csv', 'w') as fp:
                    pass
            if os.path.exists('traffic.csv')==True:
                if os.stat('traffic.csv').st_size>1024*2:
                    print('file size already bigger than allowed')
                else:

                    while ((os.stat('traffic.csv').st_size) < 1024*2) == True:
                        traffic_light.append("Light turns RED at " + str(env.now))
                        df = pd.DataFrame(traffic_light)
                        df.to_csv('traffic.csv')




# env is the environment variable 

env = simpy.Environment()

# The process defined by the function Traffic_Light(env)
# is added to the environment
env.process(Traffic_Light(env))

# The process is run for the first 180 seconds (180 is not included)
env.run(until = 5000)
'''if os.path.exists('traffic.csv')!=True:
    with open('traffic.csv', 'w') as fp:
        pass
while ((os.stat('traffic.csv').st_size) < 1024)==True:
        df = pd.DataFrame(traffic_light)
        df.to_csv('traffic.csv')'''
print((os.stat('traffic.csv').st_size))